CUDA_VISIBLE_DEVICES=7 python ./src/math/train_gsm8k.py \
    --base_model ./models/Qwen2.5-1.5B \
    --data_path ./data/gsm8k \
    --save_model_path ./models/Qwen2.5-1.5B_tuned/gsm8k_plain \
    --save_result_path ./output/Qwen2.5-1.5B_tuned/gsm8k_plain \
    --bf16 \
    --do_eval \
    --learning_rate 1e-5 \
    --train_batch_size 4 \
    --epoch 2 \
    --logging_steps 2000 \
    --max_new_tokens 2048 \
    --seed 42