CUDA_VISIBLE_DEVICES=5 python ./src/math/train_latent_aug.py \
    --base_model ./models/Qwen2.5-1.5B \
    --data_path ./data/gsm8k \
    --aug_data_path ./data/gsm8k_aug \
    --save_model_path ./models/Qwen2.5-1.5B_latent/gsm8k_aug_multihot_ronly \
    --save_result_path ./output/Qwen2.5-1.5B_latent/gsm8k_aug_multihot_ronly \
    --bf16 \
    --do_eval \
    --learning_rate 1e-5 \
    --grad_clip 1 \
    --train_batch_size 4 \
    --epoch 2 \
    --logging_steps 100 \
    --max_new_tokens 2048 \
    --intermediate_result_only \
    --int_precision 10 \
    --frac_precision 5 \
    --report_to none \
    --seed 42